# Extreme Reactors Create Compat - mods.toml

modLoader="javafml"
loaderVersion="[47,49)"

# The license for you mod. This is mandatory metadata and allows for easier comprehension of your redistributive properties.
# Review your options at https://choosealicense.com/. All rights reserved is the default copyright stance, and is thus the default here.
license="All rights reserved"

# A URL to refer people to when problems occur with this mod
issueTrackerURL="https://github.com/ZeroNoRyouki/ExtremeReactors2"
logoFile="logo.png"

[[mods]]

	modId="er2create"
    version="${file.jarVersion}"
    updateJSONURL="https://raw.githubusercontent.com/ZeroNoRyouki/ModUpdates/master/er2create.json"
	displayName="Extreme Reactors Create Compat"
	authors="ZeroNoRyouki"
	description="Create compatibility module for Extreme Reactors"

[[dependencies.er2create]]

    modId="minecraft"
    mandatory=true
    versionRange="[1.20.1,1.21)"
    ordering="NONE"
    side="BOTH"
	
[[dependencies.er2create]]

	modId="forge"
	mandatory=true
    versionRange="[47.1.1,49)"
	ordering="NONE"
	side="BOTH"

[[dependencies.er2create]]

    modId="zerocore"
    mandatory=true
    versionRange="[1.20.1-2.1.40,1.21-2.2.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.er2create]]

    modId="bigreactors"
    mandatory=true
    versionRange="[1.20.1-2.0.76,1.21-2.1.0)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.er2create]]

    modId="create"
    mandatory=true
    versionRange="[0.5.1.e-24,)"
    ordering="AFTER"
    side="BOTH"
